sudo: required
services:
  - docker

before_install:
  - docker build -t smcook55/react-test --file ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true smcook55/react-test npm test

after_success:
  - docker build -t smcook55/multi-client ./client
  - docker build -t smcook55/multi-nginx ./nginx
  - docker build -t smcook55/multi-server ./server
  - docker build -t smcook55/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  # Push images to dockerhub
  - docker push smcook55/multi-client
  - docker push smcook55/multi-nginx
  - docker push smcook55/multi-server
  - docker push smcook55/multi-worker