version: '3'

services:
  nginx:
    restart: always
    image: smcook55/multi-nginx
    ports:
      - '80:80'
  api:
    image: smcook55/multi-server
    environment:
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      PGUSER: $PGUSER
      PGHOST: $PGHOST
      PGDATABASE: $PGDATABASE
      PGPASSWORD: $PGPASSWORD
      PGPORT: $PGPORT
  client:
    image: smcook55/multi-client
  worker:
    image: smcook55/multi-worker
    environment:
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT